---
Parameters:
  SecurityGroupDescription:
    Description: Security Group Description
    Type: String
    Default: Enable SSH and HTTP
  KeyName:
    Description: Name of existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName
    

Resources:
  AnsibleTower:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2a
      ImageId: ami-0d8d212151031f51c
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref SSHandHTTPSG


  # our EC2 security group
  SSHandHTTPSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80

