---
  - name: ilovenano
    become: yes
    hosts: all
    tasks:
      - name: ensure nano is installed
        apt:
          name: nano
          state: latest

      - name: ensure httpd is installed
        apt:
          name: apache2
          state: latest

      - name: esure httpd is running
        service:
          name: apache2
          state: started
          enabled: yes

==========
---
- hosts: all
  become: yes
  tasks:
    - apt: name=nano state=latest
    - apt: name=apache2 state=present
    - service: name=apache2 state=started enabled=yes
